port: 90
hosts:
- name: content.localhost
  paths:
  - path: /v0
    name: content service
    protocol: "http:"
    port: 91
    entryPoint: ../content/main.js
- name: api.localhost
  paths:
  - path: /v0
    name: api service
    protocol: "http:"
    port: 92
    entryPoint: ../api/main.js 
# define other hosts here:
